export const debugQuests = [
  {
    id: 'debugQuest1',
    icon: 'elven_riot',
    title: 'Put down the elven revolt',
    description: 'Arrogant elves want people to get out of their sacred woods.\nTeach these sharp-eared some good manners!',
    victoryMsg: 'Haha! Now these sharp-eared bastards know who is the boss!',
    defeatMsg: 'Oops! Seems like you have failed to sort out this mess...',
    duration: 3,
    reward: {xp: 10},
    penalty: {hp: 10}
  },
];
export const quests = [
  {
    id: 1,
    icon: 'elven_riot',
    title: 'Put down the elven revolt',
    description: 'Arrogant elves want people to get out of their sacred woods.\nTeach these sharp-eared some good manners!',
    victoryMsg: 'Haha! Now these sharp-eared bastards know who is the boss!',
    defeatMsg: 'Oops! Seems like you have failed to sort out this mess...',
    duration: 600,
    reward: {xp: 10},
    penalty: {hp: 10}
  },
  {
    id: 2,
    icon: 'ghost_warriors',
    title: 'Make ghost warriors rest in peace',
    description: 'Mighty soldiers are seeking battles after death.\nHelp them find peace!',
    victoryMsg: 'Yeah! Who you gonna call? Ghostbusters!',
    defeatMsg: 'Now, they kicked your ass...',
    duration: 600,
    reward: {xp: 10},
    penalty: {hp: 10}
  },
  {
    id: 3,
    icon: 'save_the_princess',
    title: 'Save the princess from the savage',
    description: 'Local king\'s daughter was kidnapped by a brute.\nFind this caveman and bring the princess back!',
    victoryMsg: 'Great! You have rescued this little crowned honey!',
    defeatMsg: 'The caveman has beaten you...',
    duration: 600,
    reward: {xp: 10},
    penalty: {hp: 10}
  },
  {
    id: 4,
    icon: 'trolls',
    title: 'Defeat the troll shaman',
    description: 'Supid trolls are planning some dark ritual.\nWithout their spiritual leader they will be harmless.',
    victoryMsg: 'Hooray! Trolls are beaten!',
    defeatMsg: 'Seems like this guy with a drum and a stick is too tough for you...',
    duration: 600,
    reward: {xp: 10},
    penalty: {hp: 10}
  },
  {
    id: 5,
    icon: 'zombies',
    title: 'Protect the town from zombies',
    description: 'Local cemetery is full of zombies after some dark ritual.\nCitizens need your help!',
    victoryMsg: 'No zombies in town on my shift!',
    defeatMsg: 'Aargh... These zombies got some braaains tonight...',
    duration: 600,
    reward: {xp: 10},
    penalty: {hp: 10}
  },
  {
    id: 6,
    icon: 'crazy_dwarf_inventor',
    title: 'Stop the crazy dwarf inventor',
    description: 'After being fired by the king, crazy dwarf inventor is seeking for revenge.\nYou must stop him and demolish his doomsday device!',
    victoryMsg: 'Off you go, professor!',
    defeatMsg: '3..2..1..Boom!',
    duration: 1200,
    reward: {xp: 20},
    penalty: {hp: 20}
  },
  {
    id: 7,
    icon: 'defender_of_the_sacred_flame',
    title: 'Defeat the defender of the sacred flame',
    description: 'The Temple of the Sun is hiding a lot of interesting secrets.\nTo get them you need to defeat the mighty defender!',
    victoryMsg: 'Gold, gold, gold!',
    defeatMsg: 'The guy is too hot for you...',
    duration: 1200,
    reward: {xp: 20},
    penalty: {hp: 20}
  },
  {
    id: 8,
    icon: 'necromancer',
    title: 'Don\'t let the necromancer raise the army of undead',
    description: 'Insane mage is planning to conquer the kingdom by raising the army of the fallen.\nDon\'t let that happen!',
    victoryMsg: 'No more bones tonight!',
    defeatMsg: 'I see dead people... They are everywhere...',
    duration: 1200,
    reward: {xp: 20},
    penalty: {hp: 20}
  },
  {
    id: 9,
    icon: 'queen_of_the_forest',
    title: 'Capture the elusive queen of the forest',
    description: 'Little pixie has tricked king\'s soldiers and stolen the gold they have been escorting.\nCall her to account!',
    victoryMsg: 'Gotcha, you little pixie!',
    defeatMsg: 'At least that was fun...',
    duration: 1200,
    reward: {xp: 20},
    penalty: {hp: 20}
  },
  {
    id: 10,
    icon: 'witches',
    title: 'Stop the insolent witches',
    description: 'Local withces are turning local folks into frogs.\nThey think i\'s funny!',
    victoryMsg: 'No more brooms and pointy hats here!',
    defeatMsg: 'Oh, sh... Ribbit! Ribbit!',
    duration: 1200,
    reward: {xp: 20},
    penalty: {hp: 20}
  },
  {
    id: 11,
    icon: 'dutchess_of_the_darkness',
    title: 'Banish the dutchess of the darkness',
    description: 'Noble aristocrat is draining blood from the peasants.\nStop her!',
    victoryMsg: 'Take some silver and garlic!',
    defeatMsg: 'She was too beautiful to kill, yeah...',
    duration: 1800,
    reward: {xp: 30},
    penalty: {hp: 30}
  },
  {
    id: 12,
    icon: 'gnoll_master',
    title: 'Outfight the gnoll master',
    description: 'The local forest is the home for a mighty gnoll.\nBring his head to the king!',
    victoryMsg: 'Her\'s the head, you majesty!',
    defeatMsg: 'Now, wh\'s a good boy? Not you...',
    duration: 1800,
    reward: {xp: 30},
    penalty: {hp: 30}
  },
  {
    id: 13,
    icon: 'ice_monster',
    title: 'Melt the ice monster',
    description: 'On the top of the forever frozen mountain lives the ice beast.\nMake him feel hot!',
    victoryMsg: 'As simple as H2O!',
    defeatMsg: 'This piece of ice has some teeth...',
    duration: 1800,
    reward: {xp: 30},
    penalty: {hp: 30}
  },
  {
    id: 14,
    icon: 'spider_matriarch',
    title: 'Protect the temple from the spider matriarch',
    description: 'A giant spider wants to profane the local temple and use it as a nest for its brood.\nProtect the sanctuary!',
    victoryMsg: 'Good job! The goddess is satisfied!',
    defeatMsg: 'Spiders! Spiders everywhere!...',
    duration: 1800,
    reward: {xp: 30},
    penalty: {hp: 30}
  },
  {
    id: 15,
    icon: 'yeti',
    title: 'Knock out the scary winter yeti',
    description: 'They say the big snow man does not exist.\nBut people keep on disappearing...',
    victoryMsg: 'Take that, bigfoot!',
    defeatMsg: 'No more caves...',
    duration: 1800,
    reward: {xp: 30},
    penalty: {hp: 30}
  },
  {
    id: 16,
    icon: 'dark_lab',
    title: 'Demolish the dark lab',
    description: 'Crazy scientist has built a lab and is trying to reanimate a dead hooligan.\nDon\'t let that happen!',
    victoryMsg: 'Take that, Einstein!',
    defeatMsg: 'I\'ve never liked that science...',
    duration: 2400,
    reward: {xp: 40},
    penalty: {hp: 40}
  },
  {
    id: 17,
    icon: 'dark_warrior',
    title: 'Exorcise the dark warrior',
    description: 'A legendary warrior of the past is seeking for glory on a battlefield.\nShow him his place!',
    victoryMsg: 'Yeah! R.I.P. you, ghosty bastard!',
    defeatMsg: 'I have never trusted exorcists...',
    duration: 2400,
    reward: {xp: 40},
    penalty: {hp: 40}
  },
  {
    id: 18,
    icon: 'orc_chieftain',
    title: 'Hammer the orc chieftain',
    description: 'Orcs are on the rise and their chieftain is planning a raid on the kingdom.\nHe needs to be taught some manners!',
    victoryMsg: 'This is my kingdom!',
    defeatMsg: 'Aargh...',
    duration: 2400,
    reward: {xp: 40},
    penalty: {hp: 40}
  },
  {
    id: 19,
    icon: 'phoenix',
    title: 'Encage the mighty phoenix',
    description: 'There is a legendary bird that revives from ash.\nBring it to the king before it burns you!',
    victoryMsg: 'Bird is in the cage!',
    defeatMsg: 'That was too hot...',
    duration: 2400,
    reward: {xp: 40},
    penalty: {hp: 40}
  },
  {
    id: 20,
    icon: 'rotten_tree',
    title: 'Stump out the rotten tree',
    description: 'The forest is plagued.\nThe reason is the millenial living evil tree in the middle...',
    victoryMsg: 'Game over, dirty stub!',
    defeatMsg: 'No more herbology tonight...',
    duration: 2400,
    reward: {xp: 40},
    penalty: {hp: 40}
  },
  {
    id: 21,
    icon: 'bone_dragon',
    title: 'Crush the bone dragon',
    description: 'That might be a trick of a crazy necromancer.\nYou need to stop that nightmare!',
    victoryMsg: 'So many bones! Hooch will be happy!',
    defeatMsg: 'At least there is no fire in it...',
    duration: 3000,
    reward: {xp: 50},
    penalty: {hp: 50}
  },
  {
    id: 22,
    icon: 'fallen_angel',
    title: 'Pluck a fallen angel',
    description: 'Fallen angel has betrayed God.\nFace him in a fair battle!',
    victoryMsg: 'Amen!',
    defeatMsg: 'Probably, not my day...',
    duration: 3000,
    reward: {xp: 50},
    penalty: {hp: 50}
  },
  {
    id: 23,
    icon: 'ifreet',
    title: 'Сork the ifreet inside the bottle',
    description: 'The rebellious spirit has broken free and is destroying everything it sees.\nCalm it down!',
    victoryMsg: 'Now here are my three wishes!',
    defeatMsg: 'No more magic tonight...',
    duration: 3000,
    reward: {xp: 50},
    penalty: {hp: 50}
  },
  {
    id: 24,
    icon: 'red_dragon',
    title: 'Stamp a fire out of the red dragon',
    description: 'Elders say there is a red dragon somewhere in the mountains.\nThey also say the drago\'s blood is extremely valuable...',
    victoryMsg: 'I\'m the dragon slayer!',
    defeatMsg: 'This overgrown reptile has some teeth...',
    duration: 3000,
    reward: {xp: 50},
    penalty: {hp: 50}
  },
  {
    id: 25,
    icon: 'temple_of_the_black_sun',
    title: 'Demolish the temple of the black sun',
    description: 'Tne ancient order is going to perform a ritual of putting out the sun.\nStop it at any cost!',
    victoryMsg: 'Time to have some sunbaths!',
    defeatMsg: 'It was shining too bright anyway...',
    duration: 3000,
    reward: {xp: 50},
    penalty: {hp: 50}
  },
  {
    id: 26,
    icon: 'azgamoth',
    title: 'Don\'t let Azgamoth open the dark portal',
    description: 'Dark demon is opening a portal for massive imp invasion.\nStop the ritual!',
    victoryMsg: 'Hold your horns, demon!',
    defeatMsg: 'Hell no...',
    duration: 3600,
    reward: {xp: 60},
    penalty: {hp: 60}
  },
  {
    id: 27,
    icon: 'black_dragon',
    title: 'Get the black drago\'s treasure',
    description: 'You have chased the black dragon to its lair.\nTime to defeat the beast and get the gold!',
    victoryMsg: 'I am rich. Rich!!!',
    defeatMsg: 'That reptile is tough...',
    duration: 3600,
    reward: {xp: 60},
    penalty: {hp: 60}
  },
  {
    id: 28,
    icon: 'fire_golem',
    title: 'Protect the city from the fire golem',
    description: 'The volcano nearby has awakened and the fire golem is threating the city!',
    victoryMsg: 'No more marching pieces of magma!',
    defeatMsg: 'That was not a nice place, anyway...',
    duration: 3600,
    reward: {xp: 60},
    penalty: {hp: 60}
  },
  {
    id: 29,
    icon: 'leviathan',
    title: 'Fight Leviathan underwater',
    description: 'The beast of the ocean scuttles the ships.\nTime to teach the big fish some manners!',
    victoryMsg: 'Glug-glug, motherfukka!',
    defeatMsg: 'Take it easy, you big fish...',
    duration: 3600,
    reward: {xp: 60},
    penalty: {hp: 60}
  },
  {
    id: 30,
    icon: 'lucifer',
    title: 'Defeat Lucifer',
    description: 'The Son of the Satan is planning to conquer the world.\nSend him back to hell!',
    victoryMsg: 'Go to hell, bastard!',
    defeatMsg: 'What the hell?...',
    duration: 3600,
    reward: {xp: 60},
    penalty: {hp: 60}
  },
];
